#define FLEX_COMPRESSED
/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header: flex.skel,v 2.0 89/06/20 15:49:46 vern Locked $
 */

#include <stdio.h>

/* ------------------------ */
/* Questo l'ho aggiunto io: */
#ifdef __STDC__
  #include <stdlib.h>
#endif
/* ------------------------ */


#define FLEX_SCANNER

/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#ifdef  LIM64K
#define YY_READ_BUF_SIZE 1024
#else
#define YY_READ_BUF_SIZE 8192
#endif
#endif

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of input buffer */
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

#define ECHO fputs( yytext, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
        result = fread( buf, 1, max_size, yyin ); \
	if ( ferror(yyin) ) \
	    YY_FATAL_ERROR( "fread() in flex scanner failed" );

#define YY_NULL 0
#define yyterminate() return ( YY_NULL )

/* report a fatal error */
#define YY_FATAL_ERROR(msg) \
	{ \
	fputs( msg, stderr ); \
	putc( '\n', stderr ); \
	exit( 1 ); \
	}

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE goto new_file

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#ifdef __STDC__
#define YY_DECL int yylex( void )
#else
#define YY_DECL int yylex()
#endif

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = (char *)yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

/* returns the length of the matched text */
#define yyleng (yy_cp - yy_bp)

#define EOB_ACT_RESTART_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	{ \
	*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
	yy_c_buf_p = yy_cp = yy_bp + n; \
	YY_DO_BEFORE_ACTION; /* set up yytext again */ \
	}

#define unput(c) yyunput( c, yy_bp )

#define YY_USER_ACTION

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
char *yytext;

#ifndef __STDC__
#define const
#endif

#define INITIAL 0
/* yylex.l */
/* by Cristian Ghezzi - (c) 1995 */
#include <stdio.h>
#include <string.h>
#include "defs.h"
#include "procs.h"
#include "v2c.h"

void getrem(char *s, int skip);
void getstring(void);
void getstr(void);

extern int lineno;
extern YYSTYPE yylval;

static char buffer[1024];
#define YY_END_OF_BUFFER 55
typedef int yy_state_type;
static const short int yy_accept[374] =
    {   0,
        0,    0,   55,   53,    1,    5,   53,   51,   53,   52,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,    0,   50,
       51,    0,   52,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   31,    9,    7,   51,
       51,   51,   51,   51,   47,   19,   42,   45,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   15,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,

       51,   51,   51,   51,   51,   51,   51,   51,   51,    9,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,    0,    2,   51,   44,   51,   51,   11,   51,
       51,   51,   51,   17,   51,   51,   51,   37,   51,   51,
       51,   51,   51,   22,   51,   10,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   46,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,

       51,   51,   51,   51,   51,   51,   51,   34,   51,   27,
       51,   51,   51,   39,   51,   51,   51,   35,   38,   51,
        8,   51,   51,   51,   51,   51,   51,   32,   51,    0,
       51,   40,   23,   51,   24,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,    0,   51,   51,   43,   51,   21,
       28,   51,   33,   51,   49,   51,   51,   51,   51,   51,
       51,   14,   51,   51,   51,   41,    0,    4,   51,   36,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,    0,   51,   51,   16,    6,   51,   51,   51,

       26,   51,   51,   25,   20,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   13,   51,   51,   29,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,    0,   51,   51,   30,   51,   51,    0,   51,   51,
       51,   51,    0,    3,   51,   51,   51,   51,    0,   51,
       51,   51,   48,   11,   51,   11,   51,   51,   51,   51,
       18,   51,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   12,    0
    } ;

static const char yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    5,    7,    5,    5,    5,    5,
        5,    5,    5,    5,    8,    9,    5,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    5,    5,    5,
        5,    5,    5,    5,   11,   12,   13,   14,   15,   16,
       17,   18,   19,    7,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,    7,
        5,    5,    5,    5,   35,    5,   36,   37,   38,   39,

       40,   41,   42,   43,   44,    7,   45,   46,   47,   48,
       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,    7,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const char yy_meta[60] =
    {   0,
        1,    1,    1,    2,    2,    2,    3,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3
    } ;

static const short int yy_base[381] =
    {   0,
        0,    0,  449,  450,  450,  450,  442,    0,  439,  436,
       44,   47,  434,  420,   42,  419,   53,   53,   46,   62,
       55,  414,  430,   65,   69,   60,  429,   79,  415,   54,
       59,  402,  388,   61,  387,   60,   74,   71,   73,   63,
      382,  398,   82,   86,   84,  397,   95,  383,  425,  450,
        0,  427,  419,  399,  413,  413,  408,  395,  399,  394,
      389,  392,  116,  404,  399,  390,    0,  387,    0,  387,
      402,  389,  379,  382,    0,    0,    0,    0,  392,  380,
      381,  383,  387,  382,  383,  386,  388,  386,    0,  371,
      384,  371,  378,   81,  367,  368,  340,  354,  354,  349,

      336,  340,  335,  330,  333,   94,  345,  340,  331,  328,
      328,  343,  330,  320,  323,  333,  321,  322,  324,  328,
      323,  324,  327,  329,  327,  312,  325,  312,  319,  100,
      308,  309,  357,  450,  344,    0,  340,  338,    0,  343,
      340,  331,  127,    0,  334,  329,  322,    0,  335,  320,
      321,  322,  317,    0,  330,    0,  315,  330,  320,  324,
      325,  316,  303,  314,  317,  331,  315,  304,  309,  310,
      312,    0,  289,  285,  283,  288,  285,  276,  103,  279,
      274,  267,  280,  265,  266,  267,  262,  275,  260,  275,
      265,  269,  270,  261,  273,  259,  262,  301,  260,  249,

      254,  255,  257,  272,  279,  274,  276,    0,  266,    0,
      278,  264,  263,    0,  274,  255,  278,    0,    0,  261,
        0,  272,  251,  270,  271,  272,  252,    0,  260,  277,
      268,    0,    0,  263,    0,  225,  232,  227,  229,  219,
      231,  217,  216,  227,  233,  231,  214,  225,  229,  223,
      224,  225,  205,  213,  255,  221,  216,    0,  226,    0,
        0,  230,    0,  219,    0,  237,  220,  223,  221,  220,
      219,    0,  217,  224,  223,    0,  240,  450,  230,    0,
      187,  191,  180,  198,  181,  184,  182,  181,  180,  178,
      185,  184,  226,  191,  212,    0,    0,  199,  214,  190,

        0,  195,  193,    0,    0,  197,  199,  179,  166,  181,
      157,  162,  160,  164,  166,  198,    0,  189,  205,    0,
      197,  190,  191,  167,  158,  199,  166,  159,  160,  170,
      168,  194,  167,  176,    0,  140,  138,  189,  137,  146,
      159,  173,  184,  450,  171,  172,  129,  143,  179,  141,
      142,  152,    0,  143,  125,  141,  160,  143,  133,  116,
        0,  156,  130,  156,  130,  138,  112,  117,   85,   89,
       52,    0,  450,  147,   83,  150,  153,  156,  159,  162
    } ;

static const short int yy_def[381] =
    {   0,
      373,    1,  373,  373,  373,  373,  374,  375,  373,  373,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  374,  373,
      375,  376,  373,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,

      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  376,  373,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,

      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  377,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  378,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  377,  373,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  378,  375,  375,  375,  375,  375,  375,  375,

      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  379,  375,  375,  375,  375,  375,  380,  375,  375,
      375,  375,  379,  373,  375,  375,  375,  375,  380,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,    0,  373,  373,  373,  373,  373,  373,  373
    } ;

static const short int yy_nxt[510] =
    {   0,
        4,    5,    6,    5,    4,    7,    8,    9,    4,   10,
       11,   12,   13,   14,   15,   16,    8,    8,   17,    8,
       18,    8,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,    8,    8,   30,   31,   32,   33,   34,
       35,    8,    8,   36,    8,   37,    8,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,    8,   54,
       73,   57,   62,   70,   63,   58,   55,   59,   67,   74,
       56,   71,   64,   75,   65,   68,   72,   76,   81,   85,
       69,   82,   90,   86,   77,   51,   88,   91,   78,   93,
       79,   80,   89,   87,   97,  169,   94,   95,  100,  170,

       67,   98,  101,  372,  102,   99,  105,  110,  106,  111,
      114,  118,   69,   76,  119,  372,  107,  112,  108,  115,
       77,  122,  113,   75,   78,  123,  116,  117,  125,  144,
      129,  126,  144,  371,   89,  124,  127,  130,  131,  201,
      370,  210,  210,  202,  145,  211,  241,  180,   49,   49,
      133,  133,  133,  277,  277,  277,  293,  293,  293,  343,
      343,  343,  349,  349,  349,  369,  368,  367,  366,  365,
      364,  363,  361,  362,  361,  360,  359,  358,  357,  356,
      139,  344,  353,  355,  354,  139,  344,  353,  352,  351,
      350,  344,  348,  347,  346,  345,  344,  342,  341,  335,

      340,  339,  338,  337,  336,  335,  334,  333,  332,  331,
      330,  329,  328,  327,  320,  326,  325,  317,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  278,  314,
      305,  304,  313,  312,  301,  311,  310,  309,  297,  296,
      308,  307,  278,  306,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  296,  295,  280,  294,  278,  276,  292,
      291,  290,  272,  289,  288,  287,  286,  285,  284,  265,
      283,  263,  282,  261,  260,  281,  258,  280,  279,  278,
      276,  275,  274,  273,  272,  271,  270,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  235,

      257,  233,  232,  256,  255,  254,  228,  253,  252,  251,
      250,  249,  248,  221,  247,  219,  218,  246,  245,  244,
      214,  243,  242,  240,  208,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  227,  226,  225,
      224,  223,  222,  221,  220,  219,  218,  217,  216,  215,
      214,  213,  212,  209,  208,  207,  206,  205,  204,  134,
      172,  203,  200,  199,  198,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  156,  188,  154,  187,  186,  185,
      184,  183,  148,  182,  181,  179,  178,  177,  176,  139,
      175,  174,  136,  173,  172,  171,  168,  167,  166,  165,

      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  147,  146,  143,
      142,  141,  140,  139,  138,  137,  136,  135,   53,  134,
       50,  132,  128,  121,  120,  109,  104,  103,   96,   92,
       84,   83,   66,   61,   60,   53,   52,   50,  373,    3,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,

      373,  373,  373,  373,  373,  373,  373,  373,  373
    } ;

static const short int yy_chk[510] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   11,
       19,   12,   15,   18,   15,   12,   11,   12,   17,   19,
       11,   18,   15,   19,   15,   17,   18,   20,   21,   24,
       17,   21,   26,   24,   20,  375,   25,   26,   20,   28,
       20,   20,   25,   24,   30,   94,   28,   28,   31,   94,

       36,   30,   31,  371,   31,   30,   34,   36,   34,   37,
       38,   40,   36,   39,   40,  370,   34,   37,   34,   38,
       39,   43,   37,   38,   39,   43,   39,   39,   44,   63,
       47,   45,  106,  369,   44,   43,   45,   47,   47,  130,
      368,  143,  179,  130,   63,  143,  179,  106,  374,  374,
      376,  376,  376,  377,  377,  377,  378,  378,  378,  379,
      379,  379,  380,  380,  380,  367,  366,  365,  364,  363,
      362,  360,  359,  358,  357,  356,  355,  354,  352,  351,
      350,  349,  348,  347,  346,  345,  343,  342,  341,  340,
      339,  338,  337,  336,  334,  333,  332,  331,  330,  329,

      328,  327,  326,  325,  324,  323,  322,  321,  319,  318,
      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  303,  302,  300,  299,  298,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  279,  277,  275,  274,  273,  271,  270,  269,  268,
      267,  266,  264,  262,  259,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  234,  231,  230,
      229,  227,  226,  225,  224,  223,  222,  220,  217,  216,
      215,  213,  212,  211,  209,  207,  206,  205,  204,  203,

      202,  201,  200,  199,  198,  197,  196,  195,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  178,  177,  176,  175,  174,  173,  171,
      170,  169,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  155,  153,  152,  151,  150,  149,
      147,  146,  145,  142,  141,  140,  138,  137,  135,  133,
      132,  131,  129,  128,  127,  126,  125,  124,  123,  122,
      121,  120,  119,  118,  117,  116,  115,  114,  113,  112,
      111,  110,  109,  108,  107,  105,  104,  103,  102,  101,
      100,   99,   98,   97,   96,   95,   93,   92,   91,   90,

       88,   87,   86,   85,   84,   83,   82,   81,   80,   79,
       74,   73,   72,   71,   70,   68,   66,   65,   64,   62,
       61,   60,   59,   58,   57,   56,   55,   54,   53,   52,
       49,   48,   46,   42,   41,   35,   33,   32,   29,   27,
       23,   22,   16,   14,   13,   10,    9,    7,    3,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,
      373,  373,  373,  373,  373,  373,  373,  373,  373,  373,

      373,  373,  373,  373,  373,  373,  373,  373,  373
    } ;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
static unsigned char *yy_c_buf_p;	/* points to current character in buffer */
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* true when we've seen an EOF for the current input file */
static int yy_eof_has_been_seen;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */

/* yy_ch_buf has to be 2 characters longer than YY_BUF_SIZE because we need
 * to put in 2 end-of-buffer characters (this is explained where it is
 * done) at the end of yy_ch_buf
 */
static unsigned char yy_ch_buf[YY_BUF_SIZE + 2];

/* yy_hold_char holds the character lost when yytext is formed */
static unsigned char yy_hold_char;

static yy_state_type yy_last_accepting_state;
static unsigned char *yy_last_accepting_cpos;

#ifdef __STDC__
static yy_state_type yy_get_previous_state( void );
static int yy_get_next_buffer( void );
static void yyunput( int c, unsigned char *buf_ptr );
static int input( void );
static void yyrestart( FILE *input_file );
#else
static yy_state_type yy_get_previous_state();
static int yy_get_next_buffer();
static void yyunput();
static int input();
static void yyrestart();
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register unsigned char *yy_cp, *yy_bp;
    register int yy_act;





    if ( yy_init )
	{
	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

new_file:
	/* this is where we enter upon encountering an end-of-file and
	 * yywrap() indicating that we should continue processing
	 */

	/* we put in the '\n' and start reading from [1] so that an
	 * initial match-at-newline will be true.
	 */

	yy_ch_buf[0] = '\n';
	yy_n_chars = 1;

	/* we always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yy_eof_has_been_seen = 0;

	yytext = (char *)(yy_c_buf_p = &yy_ch_buf[1]);
	yy_hold_char = *yy_c_buf_p;
	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
	do
	    {
	    register unsigned char yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 374 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 373 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;

	/* bogus while loop to let YY_BACK_TRACK, EOB_ACT_LAST_MATCH,
	 * and EOF actions branch here without introducing an optimizer-
	 * daunting goto
	 */
	while ( 1 )
	    {
	    yy_act = yy_accept[yy_current_state];

	    YY_DO_BEFORE_ACTION;
	    YY_USER_ACTION;

#ifdef FLEX_DEBUG
	    fprintf( stderr, "--accepting rule #%d (\"%s\")\n",
		     yy_act, yytext );
#endif

do_action:	/* this label is used only to access EOF actions */
	    switch ( yy_act )
		{
		case 0: /* must backtrack */
		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;
		yy_cp = yy_last_accepting_cpos;
		yy_current_state = yy_last_accepting_state;
		continue; /* go to "YY_DO_BEFORE_ACTION" */

case 1:
{;}
	YY_BREAK
case 2:
{ getrem("", 2); return REM; }
	YY_BREAK
case 3:
{
    warning("'library' statement ignored");
    getrem(" library", 7); return REM;
    }
	YY_BREAK
case 4:
{
    warning("'use' statement ignored");
    getrem(" use", 3); return REM;
    }
	YY_BREAK
case 5:
{ lineno++; fprintf(stderr, "Line:%4d\r", lineno); }
	YY_BREAK
case 6:
{ return ENTITY; }
	YY_BREAK
case 7:
{ return IS; }
	YY_BREAK
case 8:
{ return PORT; }
	YY_BREAK
case 9:
{ return IN; }
	YY_BREAK
case 10:
{ return OUT; }
	YY_BREAK
case 11:
{ return BIT; }
	YY_BREAK
case 12:
{ return STD_ULOGIC_VECTOR; }
	YY_BREAK
case 13:
{ return INTEGER; }
	YY_BREAK
case 14:
{ return RANGE; }
	YY_BREAK
case 15:
{ return TO; }
	YY_BREAK
case 16:
{ return DOWNTO; }
	YY_BREAK
case 17:
{ return END; }
	YY_BREAK
case 18:
{ return ARCHITECTURE; }
	YY_BREAK
case 19:
{ return OF; }
	YY_BREAK
case 20:
{ return SIGNAL; }
	YY_BREAK
case 21:
{ return BEGN; }
	YY_BREAK
case 22:
{ return NOT; }
	YY_BREAK
case 23:
{ return WHEN; }
	YY_BREAK
case 24:
{ return WITH; }
	YY_BREAK
case 25:
{ return SELECT; }
	YY_BREAK
case 26:
{ return OTHERS; }
	YY_BREAK
case 27:
{ return ELSE; }
	YY_BREAK
case 28:
{ return BLOCK; }
	YY_BREAK
case 29:
{ return PROCESS; }
	YY_BREAK
case 30:
{ return VARIABLE; }
	YY_BREAK
case 31:
{ return IF; }
	YY_BREAK
case 32:
{ return THEN; }
	YY_BREAK
case 33:
{ return ELSIF; }
	YY_BREAK
case 34:
{ return CASE; }
	YY_BREAK
case 35:
{ return LOOP; }
	YY_BREAK
case 36:
{ return WHILE; }
	YY_BREAK
case 37:
{ return FOR; }
	YY_BREAK
case 38:
{ return NEXT; }
	YY_BREAK
case 39:
{ return EXIT; }
	YY_BREAK
case 40:
{ return WAIT; }
	YY_BREAK
case 41:
{ return UNTIL; }
	YY_BREAK
case 42:
{ return ON; }
	YY_BREAK
case 43:
{ return AFTER; }
	YY_BREAK
case 44:
{ return AND; }
	YY_BREAK
case 45:
{ return OR; }
	YY_BREAK
case 46:
{ return XOR; }
	YY_BREAK
case 47:
{ return UNIT; }
	YY_BREAK
case 48:
{ return LASTVALUE; }
	YY_BREAK
case 49:
{ return EVENT; }
	YY_BREAK
case 50:
{
   getstring();
   return STRING;
}
	YY_BREAK
case 51:
{
   getstr();
   return NAME;
}
	YY_BREAK
case 52:
{
   sscanf(yytext, "%d", &yylval.n);
   return NATURAL;
}
	YY_BREAK
case 53:
{ return yytext[0]; }
	YY_BREAK
case 54:
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
    yyterminate();

		case YY_END_OF_BUFFER:
		    /* undo the effects of YY_DO_BEFORE_ACTION */
		    *yy_cp = yy_hold_char;

		    yytext = (char *)yy_bp;

		    switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
			    {
			    if ( yywrap() )
				{
				/* note: because we've taken care in
				 * yy_get_next_buffer() to have set up yytext,
				 * we can now set up yy_c_buf_p so that if some
				 * total hoser (like flex itself) wants
				 * to call the scanner after we return the
				 * YY_NULL, it'll still work - another YY_NULL
				 * will get returned.
				 */
				yy_c_buf_p = (unsigned char *)yytext;

				yy_act = YY_STATE_EOF((yy_start - 1) / 2);
				goto do_action;
				}

			    else
				YY_NEW_FILE;
			    }
			    break;

			case EOB_ACT_RESTART_SCAN:
			    yy_c_buf_p = (unsigned char *)yytext;
			    yy_hold_char = *yy_c_buf_p;
			    break;

			case EOB_ACT_LAST_MATCH:
			    yy_c_buf_p = &yy_ch_buf[yy_n_chars];

			    yy_current_state = yy_get_previous_state();

			    yy_cp = yy_c_buf_p;
			    yy_bp = (unsigned char *)yytext;
			    continue; /* go to "YY_DO_BEFORE_ACTION" */
			}
		    break;

		default:
		    printf( "action # %d\n", yy_act );
		    YY_FATAL_ERROR( "fatal flex scanner internal error" );
		}

	    break; /* exit bogus while loop */
	    }
	}
    }


/* yy_get_next_buffer - try to read in new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH -
 *     EOB_ACT_RESTART_SCAN - restart the scanner
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()

    {
    register unsigned char *dest = yy_ch_buf;
    register unsigned char *source = (unsigned char *)yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p != &yy_ch_buf[yy_n_chars + 1] )
	{
	fprintf(stderr, "\nyy_c_buf_p = %8lx  &yy_ch_buf[%ld + 1] = %8lx\n",
	                 (long)yy_c_buf_p, (long)yy_n_chars, (long)&yy_ch_buf[yy_n_chars+1]);
	YY_FATAL_ERROR( "NULL in input" );
	/*NOTREACHED*/
	}

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - (unsigned char *)yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_eof_has_been_seen )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = YY_BUF_SIZE - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	/* read in more data */
	YY_INPUT( (&yy_ch_buf[number_to_move]), yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move == 1 )
	    ret_val = EOB_ACT_END_OF_FILE;
	else
	    ret_val = EOB_ACT_LAST_MATCH;

	yy_eof_has_been_seen = 1;
	}

    else
	ret_val = EOB_ACT_RESTART_SCAN;

    yy_n_chars += number_to_move;
    yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in
     * yy_ch_buf; the first character is the one which
     * preceded it before reading in the latest buffer;
     * it needs to be kept around in case it's a
     * newline, so yy_get_previous_state() will have
     * with '^' rules active
     */

    yytext = (char *)&yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register unsigned char *yy_cp;

    yy_current_state = yy_start;

    for ( yy_cp = (unsigned char *)yytext; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register unsigned char yy_c = yy_ec[*yy_cp];
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 374 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


#ifdef __STDC__
static void yyunput( int c, register unsigned char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register unsigned char *yy_bp;
#endif

    {
    register unsigned char *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char; /* undo effects of setting up yytext */

    if ( yy_cp < yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register unsigned char *dest = &yy_ch_buf[YY_BUF_SIZE + 2];
	register unsigned char *source = &yy_ch_buf[number_to_move];

	while ( source > yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;

	if ( yy_cp < yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


static int input()

    {
    int c;
    unsigned char *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{ /* need more input */
	yytext = (char *)yy_c_buf_p;
	++yy_c_buf_p;

	switch ( yy_get_next_buffer() )
	    {
	    /* this code, unfortunately, is somewhat redundant with
	     * that above
	     */
	    case EOB_ACT_END_OF_FILE:
		{
		if ( yywrap() )
		    {
		    yy_c_buf_p = (unsigned char *)yytext;
		    return ( EOF );
		    }

		yy_ch_buf[0] = '\n';
		yy_n_chars = 1;
		yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
		yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;
		yy_eof_has_been_seen = 0;
		yytext = (char *)(yy_c_buf_p = &yy_ch_buf[1]);
		yy_hold_char = *yy_c_buf_p;

		return ( input() );
		}
		break;

	    case EOB_ACT_RESTART_SCAN:
		yy_c_buf_p = (unsigned char *)yytext;
		break;

	    case EOB_ACT_LAST_MATCH:
		YY_FATAL_ERROR( "unexpected last match in input()" );
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef __STDC__
static void yyrestart( FILE *input_file )
#else
static void yyrestart( input_file )
FILE *input_file;
#endif

    {
    if ( yyin != stdin )
	fclose( yyin );

    yyin = input_file;
    yy_init = 1;
    }


void getstr(void)
{
sscanf(yytext, "%s", buffer);
yylval.txt=(char *)mymalloc(strlen(buffer)+1);
strcpy(yylval.txt, buffer);
}



void getrem(char *s, int skip)
{
/* Prende tutto fino a \n */
int i=0;
lineno++;
while (yytext[i+skip]!='\n')
      {
      buffer[i]=yytext[i+skip];
      i++;
      }
buffer[i]=0;
#ifdef MAI
 strcat(buffer, " */\n");
#endif

yylval.txt=(char *)mymalloc(strlen(buffer)+strlen(s)+1);
strcpy(yylval.txt, s);
strcat(yylval.txt, buffer);
}



void getstring(void)
{
/* Prende una stringa escludendo le " */
int i=0;
do {
   buffer[i]=yytext[i+1];
   ++i;
   } while (yytext[i]!='"');
buffer[i-1]=0;
yylval.txt=(char *)mymalloc(strlen(buffer)+1);
strcpy(yylval.txt, buffer);
}



/* End of yylex.l */
